name: Docker Image Deployment

on:
  push:
    branches:
      - optional
  
  
jobs:

  run_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Run test server
        run: npm run start &
        
      - name: Run tests
        run: npm test

  push_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: gprendi30/adobe_exercise
        tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=sha,format=long,prefix={{branch}}-
            type=raw,value=latest
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}